name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore CJS.MudExtensions.sln

      - name: Build
        run: dotnet build CJS.MudExtensions.sln -c Release --no-restore

      - name: Pack
        run: dotnet pack src/CJS.MudExtensions/CJS.MudExtensions.csproj -c Release --no-build
